### ISSUE TITLE
When using VNC after a while, the device completely freezes

### ISSUE THREAD

**Issue by kkeker** [pikvm/pikvm#1045] opened 2023-07-01 13:02 UTC
**Describe the bug**
When using VNC after a short time (2-5 minutes), the device completely freezes, becomes unavailable via WebUI, SSH, VNC. If you do not use VNC, but only SSH or WebUI, there are no such problems.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Configure VNC according to the official PiKVM documentation
2. Connect using any VNC client
3. Work through VNC for a few minutes
4. The device will freeze and only a hardware reboot will help

**Desktop (please complete the following information):**
 - OS: Any
 - VNC client: embedded VNC Client in macOS, Jump for iOS/iPadOS

**PiKVM info:**
Raspberry Pi Zero 2w
PiKVM platform v2-hdmi
Video capture type CSI bridge
KVMD version:
kvmd 3.231-1
kvmd-fan 0.26-1
kvmd-oled 0.23-1
kvmd-platform-v2-hdmi-zero2w 3.231-1
kvmd-webterm 0.43-1
uStreamer version: ustreamer 5.41-1
Linux kernel: Linux device 5.15.68-3-rpi-ARCH

**Additional context**
When it freezes, the green Raspberry Zero 2W indicator starts flashing. During normal operation, it burns evenly without blinking.

CPU and RAM utilization does not exceed the norm. I even tried to disable all unnecessary services for KVMD WebUI to leave only kvmd-vnc, but it didn't save me from freezing.

**Comment by mdevaev** [comment] 2023-07-01 13:51
Hello. Try to replace microsd card, it looks like a memory error. Also it can explain this: #1044

**Comment by mdevaev** [comment] 2023-07-02 11:54
Do you have another Raspberry device? It could still be RAM corruption. I've come across this several times.

**Comment by mdevaev** [comment] 2023-07-02 16:34
I know it looks weird, but I'll explain. The problem you describe doesn't occur to other users, and I can't reproduce it. However, I personally had two devices (and about five other users encountered this) that got into kernel panic due to memory corruption. 

The first option is when some parts of the SDcard are damaged and incorrect executable files are loaded into RAM. We have ruled out this option.

The second option that I have encountered is the degradation of the memory controller, which occasionally happens with Raspberry. With non-linear access, the controller turns the data into noodles and because of this, the kernel falls into kernel panic too. This cannot be detected by a linear memory test, but it is known that over time the frequency of occurrence of this error will progress. In my case, replacing the RAM chip with a Pi4 helped.

I have several devices lying here, and I have not been able to reproduce your problem at all. Given that this is extremely similar to the hardware problems I've already encountered, I'm leaning towards the fact that your Pi is broken.

**Comment by mdevaev** [comment] 2023-07-13 22:11
Hello! Any news with this?

**Comment by mdevaev** [comment] 2023-07-20 19:33
Are you using Windows on the target host?

**Comment by mdevaev** [comment] 2023-08-08 20:07
Just tu be sure, could you try the latest kvmd release?

**Comment by mdevaev** [comment] 2023-10-10 23:45
Sup?

**Comment by mdevaev** [comment] 2023-10-25 08:58
I'm closing it since we have no moving with this and I'm sure this is hardware problem.

**Closed by mdevaev** 2023-10-25 08:58 UTC
