### ISSUE TITLE
Alt+ctrl+letter does not work when connecting using Jump Desktop VNC

### ISSUE THREAD

**Issue by a-singer** [pikvm/pikvm#84] opened 2020-09-27 02:49 UTC
Hello,

I don't seem to be able to use alt+ctrl+key when connecting to the VNC server. It is as if nothing happens. Ctrl+shift+key works, as does alt+shift+key, but not ctrl+alt+key. I can use sticky keys to do this, press alt, then press ctrl, then press a key, but can't use the combination as usual. I have made no changes to the keymap, following only instructions 1, 4, and 5 on the vnc.md page. I am using the Jump Desktop VNC client on iOS, and that client does send alt+ctrl+key properly when connected to my Windows VNC server. Might changing the keymap be helpful? Thanks.

**Comment by mdevaev** [comment] 2020-09-27 16:47
Perhaps the reason is the absence of the AltGr binding. This is fixed in git, but I'll look further into what's wrong.

**Comment by a-singer** [comment] 2020-09-27 18:18
I have looked through the recent commits but have little experience on how to best handle these things, so must have missed the fix. If it would be useful to update to the new component and test, I am happy to do that. Thanks.

**Comment by mdevaev** [comment] 2020-09-30 06:44
I can't reproduce this on Tiger VNC. And right now I don't have an iOS device where I can put your client. However, I noticed that some keyboard shortcuts, such as Ctrl+Alt+X, are not really passed by the client. On the other hand, Ctrl+Alt+Space and others work. I believe that the client's own hotkeys are not transmitted.

**Comment by mdevaev** [comment] 2020-09-30 06:45
Try other possible hotkeys. Let's find out what's wrong.

**Comment by a-singer** [comment] 2020-09-30 16:48
I'm sorry, the problem is on my end, the lack of alt+control+keystrokes is only there when VoiceOver, the iOS screen reader, is on. When I turn it off, I can hit alt+ctrl+keystroke and get it passed through to the server. Again, sorry for disturbing you with it, this should be going to Apple accessibility, I'll report it to them. I should say that the windows key issue, issue  #81  is not effected by whether the screen reader is on or off. Thanks for looking into this.

**Comment by mdevaev** [comment] 2020-09-30 22:28
Okay, I'll deal with the next problem.

**Closed by mdevaev** 2020-09-30 22:28 UTC
Labels: help wanted, type:bug
