### ISSUE TITLE
"RuntimeError: Can't find any UDC" on RPI4B

### ISSUE THREAD

**Issue by makefu** [pikvm/pikvm#552] opened 2021-11-28 19:44 UTC
**Describe the bug**
i tried to get PiKVM running on my RPI4B with the C779 CSI bridge. However, when starting up and trying to connect to the webserver i get 500 server error and the kvmd console shows `RuntimeError: Can't find any UCD`

**To Reproduce**
Steps to reproduce the behavior, like:
1. Download and flash latest pikvm image onto an sdcard
2. boot rpi4b
3. browse to https://pikvm/
4. See error 500

**Expected behavior**
Application server starts up

**Screenshots**
![image](https://user-images.githubusercontent.com/115218/143783159-11e1a3c5-5652-4f14-8c00-3e989580c8d8.png)

**Desktop (please complete the following information):**
 - OS:Linux
 - Browser: Firefox

**PiKVM info:**
  - Raspberry Pi board version RPi 4B
  - PiKVM platform: v2-hdmi
  - Video capture type: CSI bridge C779
  - KVMD version: `pacman -Q | grep kvmd`:
```
kvmd 3.49-1
kvmd-fan 0.1-1
kvmd-oled 0.8-1
kvmd-platform-v2-hdmi-rpi4 3.49-1
kvmd-webterm 0.41-1
```
  - uStreamer version: `pacman -Q | grep ustreamer`: `ustreamer 4.9-1`
 
  - Linux kernel: `uname -a`: ` Linux pikvm 5.10.52-13-ARCH #1 SMP Sat Nov 20 09:40:57 MSK 2021 armv7l GNU/Linux`

**Additional context**

Related: https://old.reddit.com/r/pikvm/comments/r44zro/runtimeerror_cant_find_any_udc_on_rpi4b/

* journalctl -xu kvmd: https://p.krebsco.de/03l21c0
* journalctl -k: https://p.krebsco.de/1h7n346

**Comment by mdevaev** [comment] 2021-11-28 23:12
Please show output of the `pistat` command.

**Comment by makefu** [comment] 2021-11-29 08:07
```
[root@pikvm ~]# pistat
# Raspberry Pi 4 Model B Rev 1.1

CPU temp: 27.74'C

```
After CPU the program hangs on pikvm.
I booted Raspbian bullseye, copied over the script and ran it:
```
root@raspberrypi:~# bash ./lol
# Raspberry Pi 4 Model B Rev 1.1

CPU temp: 32.61'C
GPU temp: 32.1'C

Throttled flags: 0x0

Throttled now:  no
Throttled past: no

Undervoltage now:  no
Undervoltage past: no

Frequency capped now:  no
Frequency capped past: no
```

It seems that the vcgencmd is hanging on pikvm already

**Comment by mdevaev** [comment] 2021-11-29 08:35
Please contact me using discord PM.

**Comment by makefu** [comment] 2021-11-29 08:46
@mdevaev will do!

**Comment by makefu** [comment] 2021-11-29 11:04
@mdevaev thanks for the debugging session, I will close this issue for now, it may be related to Hardware, the board is RPI4 with Revision 1.1

**Comment by rafuz** [comment] 2021-11-30 09:00
I have the same problem on the exactly same hardware.
Has it been fixed?

**Comment by potatoattack** [comment] 2021-11-30 09:47
I'm also having this same issue after updating 10 minutes ago (hadn't updated for a few weeks).

**Comment by mdevaev** [comment] 2021-11-30 16:42
Do you have 1.1 revision of 4Gb board to?

Вт, 30 нояб. 2021 г. в 12:47, potatoattack ***@***.***>:

**Comment by mdevaev** [comment] 2021-11-30 23:19
Apparently, the issue is the incompatibility of stock firmware with the old board revision 1.1.

Please try older images and tell me which one will work fine: https://files.pikvm.org/images/

**Comment by makefu** [comment] 2021-12-01 07:53
I tested the last Image ( https://files.pikvm.org/images/v2-hdmi-rpi4-20211022.img.xz ) and the error also occurred.

**Comment by HardwoodHomelab** [comment] 2021-12-08 21:11
I'm having this same issue with a Rev. 1.2 board 4gb board.

**Comment by arch1mede** [comment] 2021-12-09 17:01
> I'm having this same issue with a Rev. 1.2 board 4gb board.

Please join discord for this issue, I have 1.2 boards and they all work.

**Comment by mdevaev** [comment] 2021-12-12 10:46
I have a suspicion that there may be an old EEPROM on your boards. Or vice versa too new. Please run:
```
pacman -Syu
pacman -S rpi-eeprom
rpi-eeprom-update
```
And post results of the last command here.

**Comment by HardwoodHomelab** [comment] 2021-12-12 11:48
I ran those commands and the output of rpi-eeprom-update is:

*** UPDATE AVAILABLE ***
BOOTLOADER: update available
   CURRENT: Thu Sep  3 12:11:43 UTC 2020 (1599135103)
    LATEST: Thu Apr 29 16:11:25 UTC 2021 (1619712685)
   RELEASE: critical (/lib/firmware/raspberrypi/bootloader/critical)

  VL805_FW: Dedicated VL805 EEPROM
     VL805: up to date
   CURRENT: 000138a1
    LATEST: 000138a1

**Comment by mdevaev** [comment] 2021-12-12 11:52
Try to update `rpi-eeprom-update -a`

**Comment by HardwoodHomelab** [comment] 2021-12-12 12:57
I updated the eeprom and rebooted the PI. The rpi-eeprom-update output now shows:

BOOTLOADER: up to date
CURRENT: Thu Apr 29 16:11:25 UTC 2021 (1619712685)
LATEST: Thu Apr 29 16:11:25 UTC 2021 (1619712685)
RELEASE: critical (/lib/firmware/raspberrypi/bootloader/critical)

VL805_FW: Dedicated VL805 EEPROM
VL805: up to date
CURRENT: 000138a1
LATEST: 000138a1

I am still getting the can't find UDC error.

**Comment by mdevaev** [comment] 2021-12-12 13:02
Try to append line `core_freq_min=250` to `/boot/config.txt`

**Comment by mdevaev** [comment] 2021-12-12 13:25
If it will not work, try following:
```
sed -i -e s/critical/stable/g /etc/default/rpi-eeprom-update
rpi-eeprom-update -a
```

**Comment by arch1mede** [comment] 2021-12-13 12:51
HardwoodHomelab's issue was not the same, I had him reflash and he reported that everything was working normally.

**Comment by mdevaev** [comment] 2021-12-13 13:49
@makefu @rafuz try reflashing on a new memory card

**Comment by mdevaev** [comment] 2021-12-16 11:00
@makefu @rafuz sup?

**Comment by arch1mede** [comment] 2021-12-16 13:46
Adding to this convo, I know someone that has a 1.1 board and after flashing, working fine

**Comment by mdevaev** [comment] 2021-12-16 13:58
Flashing EEPROM or OS?

**Comment by arch1mede** [comment] 2021-12-16 14:00
> Flashing EEPROM or OS?

OS

**Comment by mdevaev** [comment] 2021-12-16 16:28
Okay, then we believe that flashing and using another memory card helps with this.
Users, please let us know if this is not the case.

**Comment by makefu** [comment] 2021-12-17 20:56
i've got another RPI 1.4 and used the same sd card (without reflashing). The issue didn't occur.

**Comment by Martin-HiPi** [comment] 2021-12-18 00:36
The EEPROM is stored in a chip on the Pi4, so swapping the card isn't good for testing this. 
Please run `rpi-eeprom-update` and post the result here please.

To update, 
```
pacman -Syu
pacman -S rpi-eeprom
rpi-eeprom-update -a
```

Martin

**Comment by makefu** [comment] 2021-12-19 10:10
actually i ran rpi-eeprom-update when i had the 1.1 version with the same issue occurring. however due to my swap i currently do not have access to the board

**Comment by mdevaev** [comment] 2021-12-19 11:46
Soon I will make an experimental release of the kernel and we will see if there is still this problem

**Comment by DrMarlin** [comment] 2022-01-08 19:59
I have this same issue - does anyone happen to know the eeprom version that works to force a downgrade?

**Comment by mdevaev** [comment] 2022-01-08 20:41
@DrMarlin try another memory card and full reflash.

**Comment by DrMarlin** [comment] 2022-01-09 00:38
@mdevaev That did it - thanks!

**Comment by mdevaev** [comment] 2022-02-05 12:56
I'm closing it because apparently the problem is related to the memory cards

**Closed by mdevaev** 2022-02-05 12:56 UTC
Labels: type:bug
