### ISSUE TITLE
Pasting items with {} and tabs inserts unwanted additional tabs

### ISSUE THREAD

**Issue by sIKE23** [pikvm/pikvm#1327] opened 2024-05-17 15:16 UTC
have a new one for you , I have been performing a cloud migration utilizing Terraform for our IaC

when I work for home and get to use my PiKVM v3.0 I do a lot of pasting into the KVM console, as ya'll are very well aware of.
so TF uses {} for blocks of data example:

ingress {
  cidr_blocks = ["1.2.3.4/32"]
  from_port   = 8
  to_port     = 0
  protocol    = "icmp"
  description = "Allow ping from 1.2.3.4"
}
ingress {
  cidr_blocks       = ["1.2.3.4/32"]
  ipv6_cidr_blocks  = [aws_vpc.example.ipv6_cidr_block]
  from_port         = 8
  to_port           = 0
  protocol          = "icmp"
  description       = "Allow ping from 1.2.3.4 and the example.ipv6_cidr_block"
}

when I use PIKVM Text | Paste feature, this code is sent to the target but with bad formatting:
same block of code pasted in via PIKVM

ingress {
  cidr_blocks = ["1.2.3.4/32"]
    from_port   = 8
        to_port     = 0
            protocol    = "icmp"
                description = "Allow ping from 1.2.3.4"
                    }
ingress {
  cidr_blocks       = ["1.2.3.4/32"]
    ipv6_cidr_blocks  = [aws_vpc.example.ipv6_cidr_block]
        from_port         = 8
            to_port           = 0
                protocol          = "icmp"
                    description       = "Allow ping from 1.2.3.4 and the example.ipv6_cidr_block"
                        }

These are tab delimited and I suspect that the parser is doing and i+1 kind of math without resetting i on eachj line. As an experiment I changed {} to () and []  and still had the same issue. 

To reproduce paste in the properly formatted text above thought the Text | Paste feature of PIKVM.

If you have any questions, please let me know.

**Comment by mdevaev** [comment] 2024-05-26 21:53
Hello.

Users sometimes encounter this problem. The fact is that the paste function does not work as an insert, but as a very fast printing of the text that you entered. The reason for this lies in the absence of any connection between KVM and OS on the computer, that is, we cannot affect the clipboard and have to act as a keyboard.

The text editor on the target OS is too smart and inserts indents itself because it thinks you are typing on the keyboard. Turn it off and everything will work as intended. Alas, this cannot be fixed on the PiKVM side, as it does not know if your text editor will insert indents automatically.

**Closed by mdevaev** 2024-05-26 21:53 UTC
