### ISSUE TITLE
Make screenshot function download the image immediately

### ISSUE THREAD

**Issue by jernejs** [pikvm/pikvm#1443] opened 2024-12-17 22:32 UTC
Nearly every time I use the screenshot function in PiKVM, I want to save the image, but it instead shows it in a new tab; when I right-click and choose Save, the browser actually downloads a new screenshot (this happens both in Firefox and Chromium-based browsers), so what I'm saving isn't what I wanted to see.

**Comment by mdevaev** [comment] 2024-12-18 03:28
Hello. It works exactly as intended so that you can, if necessary, simply copy the image to the clipboard to send it to the messenger. Is saving really that big a problem?

**Comment by mdevaev** [comment] 2024-12-21 08:47
Closing due no feedback.

**Closed by mdevaev** 2024-12-21 08:47 UTC
