### ISSUE TITLE
sound over USB to the PI-KVM?

### ISSUE THREAD

**Issue by gitpower2017** [pikvm/pikvm#98] opened 2020-10-20 09:16 UTC
**Describe the solution you'd like**
there is the possibility that audio is also transmitted.
Maybe the RPI will report to the PC/server as a USB soundcard?

**Comment by gitpower2017** [comment] 2020-10-20 09:18
sorry for doppel posting. Ther was an error on my Browser

**Comment by mdevaev** [comment] 2020-10-20 12:24
Duplicate of #97

**Closed** 2020-10-20 12:24 UTC
Labels: resolution:duplicate, type:feature
