### ISSUE TITLE
Color calibration

### ISSUE THREAD

**Issue by shafiq-mohammed** [pikvm/pikvm#1147] opened 2023-10-31 17:59 UTC
**Is your feature request related to a problem? Please describe.**
The PiKVM is flawless except the color calibration makes it hard to work on. I'm attaching an image, on the left is how it should look like but on the pikvm the colors are distorted and gray looks like black. 

**Describe the solution you'd like**
Colors to be nice and accurate :) 

**Describe alternatives you've considered**
I've tried to select different color profiles but none of them work

**Additional context**
Add any other context or screenshots 
![Screenshot 2023-10-31 at 1 55 56 PM](https://github.com/pikvm/pikvm/assets/5553230/cf6c50df-440a-4789-bc59-d5e70f0a0881)
about the feature request here.

**Comment by mdevaev** [comment] 2023-11-03 16:07
Which browser do you use?

**Comment by arch1mede** [comment] 2023-11-20 00:50
Hi, any update to this? We have seen this type of thing before, bad cable or some night shift toggle on it, I have this connected to a mac and I do not see the same behavior, we would recommend you join [Discord](https://discord.gg/bpmXfz5) to discuss further.

**Comment by mdevaev** [comment] 2023-11-21 21:01
@shafiq-mohammed sup?

@arch1mede this was discussed in the discord, I requested diagnostics, but @shafiq-mohammed disappeared :(

**Comment by shafiq-mohammed** [comment] 2023-11-22 07:42
> Which browser do you use?

Hey i'm so sorry for the late response. I'm using google chrome. I'll run a few tests tomorrow to see if my results change. On my macbook pro that has an hdmi slot i'm not getting a color issue but on my air i have to use an hdmi to usbc and that's the device i'm getting the color calibration issue.

do you think it could be that? Will other hdmi to usbc work or is that just the nature of an hdmi to usbc cable?

any other adapters I should look into?

**Comment by mdevaev** [comment] 2023-12-03 22:36
Perhaps this may be due to some special video modes of the adapter, I have never seen this before.

**Comment by mdevaev** [comment] 2024-01-28 12:40
Sup?

**Comment by mdevaev** [comment] 2024-02-01 12:20
Presumably the problem is with the adapter. I'm closing it because there is no answer.

**Closed by mdevaev** 2024-02-01 12:20 UTC
